import { Injectable, Logger } from '@nestjs/common';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

export interface TrackSearchResult {
  id: string;
  title: string;
  artist: string;
  thumbnail: string;
  url: string;
  description: string;
}

function decodeHtmlEntities(str: string): string {
  if (!str) return '';
  return str
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#x27;/g, "'");
}

function cleanTitleAndArtist(rawTitle: string, rawChannel: string): { title: string; artist: string } {
  const decodedTitle = decodeHtmlEntities(rawTitle || '');
  const decodedChannel = decodeHtmlEntities(rawChannel || '');

  let artist = decodedChannel.replace(/\s*-\s*Topic$/i, '').trim() || 'Unknown Artist';
  let title = decodedTitle;

  // Remove common video metadata suffixes from title
  title = title.replace(
    /\s*[\(\[](official\s*(audio|music\s*video|video|visualizer|lyric\s*video|track)|audio|visualizer|clip\s*officiel|video\s*officielle)[\)\]]/gi,
    '',
  ).trim();

  // If title is in the format "Artist - Song Title", parse both
  const match = title.match(/^([^-]+)\s*-\s*(.+)$/);
  if (match) {
    artist = match[1].trim();
    title = match[2].trim();
  }

  return { title, artist };
}

function isJunkOrVideo(title: string, channel: string, desc: string): boolean {
  const t = `${title} ${channel} ${desc}`.toLowerCase();

  // Exclude non-studio, fan uploads, live concerts, fan edits
  if (/\b(live|concert|festival|tour|arena|acoustic|orchestral)\b/i.test(t)) return true;
  if (/\b(slowed|reverb|sped up|speed up|8d|bass boosted|nightcore|432hz|pitch)\b/i.test(t)) return true;
  if (/\b(instrumental|karaoke|type beat|beat|cover|remake|reprod|reproduced|fan made|tribute)\b/i.test(t)) return true;
  if (/\b(lyrics?|parody|reaction|review|interview|vlog|behind the scenes|teaser|trailer|full set)\b/i.test(t)) return true;
  if (/\b(edit|mashup|unreleased|leak|snippet)\b/i.test(t)) return true;

  return false;
}

function getTrackScore(item: any): number {
  const title = (item.snippet?.title || '').toLowerCase();
  const channel = (item.snippet?.channelTitle || '').toLowerCase();
  const desc = (item.snippet?.description || '').toLowerCase();

  // 1. YouTube Auto-generated Topic Track (Pure studio mastered audio)
  if (channel.endsWith('- topic') || /provided to youtube|auto-generated by youtube/i.test(desc)) {
    return 100;
  }
  // 2. Official Audio uploaded on artist channel
  if (/official\s*audio|official\s*track/i.test(title)) {
    return 80;
  }
  // 3. Official VEVO audio or Verified Artist channel
  if (/vevo/i.test(channel)) {
    return 60;
  }
  return 30;
}

function formatDescription(rawDescription: string, artistName: string): string {
  const decoded = decodeHtmlEntities(rawDescription || '').trim();
  if (decoded.length > 0) {
    return decoded;
  }
  return `Track by ${artistName}`;
}

function getHighResThumbnail(videoId: string, fallbackUrl?: string): string {
  if (!videoId) return fallbackUrl || '';
  return `https://i.ytimg.com/vi/${videoId}/maxresdefault.jpg`;
}

@Injectable()
export class YtApiService {
  private readonly logger = new Logger(YtApiService.name);
  private readonly baseUrl = 'https://www.googleapis.com/youtube/v3';

  /**
   * Search YouTube exclusively for official studio audio tracks.
   */
  async searchTracks(query: string, maxResults = 10): Promise<TrackSearchResult[]> {
    if (!query || !query.trim()) {
      return [];
    }

    const searchQuery = query.trim();
    const apiKey = process.env.YT_API_KEY;

    if (apiKey) {
      try {
        const results = await this.searchViaYoutubeApi(searchQuery, apiKey, maxResults);
        if (results.length > 0) {
          return results;
        }
      } catch (err: any) {
        this.logger.warn(`YouTube API search failed (${err.message}). Falling back to yt-dlp search...`);
      }
    } else {
      this.logger.log('YT_API_KEY not set. Using yt-dlp search fallback...');
    }

    return this.searchViaYtDlp(searchQuery, maxResults);
  }

  private async searchViaYoutubeApi(
    searchQuery: string,
    apiKey: string,
    maxResults: number,
  ): Promise<TrackSearchResult[]> {
    const fetchLimit = Math.max(maxResults * 2, 20);

    // Run parallel search for topic tracks and broad query
    const [topicData, generalData] = await Promise.all([
      fetch(
        `${this.baseUrl}/search?part=snippet&type=video&videoCategoryId=10&maxResults=${fetchLimit}&q=${encodeURIComponent(
          `${searchQuery} - Topic`,
        )}&key=${apiKey}`,
      )
        .then((r) => r.json())
        .catch(() => ({ items: [] })),
      fetch(
        `${this.baseUrl}/search?part=snippet&type=video&videoCategoryId=10&maxResults=${fetchLimit}&q=${encodeURIComponent(
          searchQuery,
        )}&key=${apiKey}`,
      )
        .then((r) => r.json())
        .catch(() => ({ items: [] })),
    ]);

    const deduplicatedMap = new Map<string, any>();
    for (const item of [...(topicData.items || []), ...(generalData.items || [])]) {
      const videoId = item.id?.videoId;
      if (videoId && !deduplicatedMap.has(videoId)) {
        deduplicatedMap.set(videoId, item);
      }
    }

    const allItems = Array.from(deduplicatedMap.values());

    // Filter out fan videos, concerts, live footage, slowed edits
    const validItems = allItems.filter(
      (item) => !isJunkOrVideo(item.snippet?.title || '', item.snippet?.channelTitle || '', item.snippet?.description || ''),
    );

    // Sort by official studio priority (Topic tracks > Official Audio > Verified Artist)
    validItems.sort((a, b) => getTrackScore(b) - getTrackScore(a));

    return validItems.slice(0, maxResults).map((item: any) => {
      const videoId = item.id?.videoId;
      const snippet = item.snippet || {};
      const { title, artist } = cleanTitleAndArtist(snippet.title, snippet.channelTitle);
      const fallbackThumbnail = snippet.thumbnails?.high?.url || snippet.thumbnails?.medium?.url;
      const thumbnail = getHighResThumbnail(videoId, fallbackThumbnail);
      const description = formatDescription(snippet.description, artist);

      return {
        id: videoId,
        title,
        artist,
        thumbnail,
        url: `https://www.youtube.com/watch?v=${videoId}`,
        description,
      };
    });
  }

  private async searchViaYtDlp(
    searchQuery: string,
    maxResults: number,
  ): Promise<TrackSearchResult[]> {
    try {
      const command = `yt-dlp --dump-single-json --flat-playlist --extractor-args "youtube:player_client=android" "ytsearch${maxResults}:${searchQuery.replace(/"/g, '\\"')}"`;
      const { stdout } = await execAsync(command, { maxBuffer: 10 * 1024 * 1024 });
      const data = JSON.parse(stdout);

      const entries = data.entries || [];

      return entries.slice(0, maxResults).map((entry: any) => {
        const videoId = entry.id;
        const rawChannelTitle = entry.uploader || entry.channel || '';
        const { title, artist } = cleanTitleAndArtist(entry.title || 'Unknown Title', rawChannelTitle);
        const fallbackThumbnail = entry.thumbnails?.[0]?.url;
        const thumbnail = getHighResThumbnail(videoId, fallbackThumbnail);
        const description = formatDescription(entry.description, artist);

        return {
          id: videoId,
          title,
          artist,
          thumbnail,
          url: `https://www.youtube.com/watch?v=${videoId}`,
          description,
        };
      });
    } catch (error: any) {
      this.logger.error(`yt-dlp search error: ${error.message}`);
      return [];
    }
  }
}
