import { Injectable, Logger } from '@nestjs/common';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

export interface TrackSearchResult {
  id: string;
  title: string;
  artist: string;
  thumbnail: string;
  url: string;
  description: string;
}

export interface ArtistSearchResult {
  id: string;
  name: string;
  channelTitle: string;
  thumbnail: string;
  description: string;
}

function decodeHtmlEntities(str: string): string {
  if (!str) return '';
  return str
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#x27;/g, "'");
}

function cleanArtistName(channelTitle: string): string {
  if (!channelTitle) return 'Unknown Artist';
  return channelTitle.replace(/\s*-\s*Topic$/i, '').trim();
}

function isAutoGeneratedTrack(channelTitle: string, description: string): boolean {
  const channelIsTopic = /-\s*topic$/i.test((channelTitle || '').trim());
  const descriptionHasAutoGenerated = /provided to youtube|auto-generated by youtube|autogenerated by youtube/i.test(
    description || '',
  );
  return channelIsTopic || descriptionHasAutoGenerated;
}

function formatDescription(rawDescription: string, artistName: string): string {
  const decoded = decodeHtmlEntities(rawDescription || '').trim();
  if (/autogenerated by youtube/i.test(decoded)) {
    return decoded;
  }
  if (/provided to youtube/i.test(decoded)) {
    return `${decoded}\n\nAutogenerated by YouTube`;
  }
  return `Provided to YouTube by ${artistName}\n\nAutogenerated by YouTube`;
}

function getHighResThumbnail(videoId: string, fallbackUrl?: string): string {
  if (!videoId) return fallbackUrl || '';
  return `https://i.ytimg.com/vi/${videoId}/maxresdefault.jpg`;
}

@Injectable()
export class YtApiService {
  private readonly logger = new Logger(YtApiService.name);
  private readonly baseUrl = 'https://www.googleapis.com/youtube/v3';

  /**
   * Search YouTube for official topic tracks.
   */
  async searchTracks(query: string, maxResults = 10): Promise<TrackSearchResult[]> {
    if (!query || !query.trim()) {
      return [];
    }

    const trimmedQuery = query.trim();
    const searchQuery = /-\s*topic$/i.test(trimmedQuery) ? trimmedQuery : `${trimmedQuery} - Topic`;

    const apiKey = process.env.YT_API_KEY;

    if (apiKey) {
      try {
        return await this.searchViaYoutubeApi(searchQuery, apiKey, maxResults);
      } catch (err: any) {
        this.logger.warn(`YouTube API search failed (${err.message}). Falling back to yt-dlp search...`);
      }
    } else {
      this.logger.log('YT_API_KEY not set. Using yt-dlp search fallback...');
    }

    return this.searchViaYtDlp(searchQuery, maxResults);
  }

  /**
   * Search YouTube for official - Topic artist channels.
   */
  async searchArtists(query: string, maxResults = 10): Promise<ArtistSearchResult[]> {
    if (!query || !query.trim()) {
      return [];
    }

    const trimmedQuery = query.trim();
    const searchQuery = /-\s*topic$/i.test(trimmedQuery) ? trimmedQuery : `${trimmedQuery} - Topic`;
    const apiKey = process.env.YT_API_KEY;

    if (apiKey) {
      try {
        const url = new URL(`${this.baseUrl}/search`);
        url.searchParams.set('part', 'snippet');
        url.searchParams.set('type', 'video');
        url.searchParams.set('videoCategoryId', '10');
        url.searchParams.set('q', searchQuery);
        url.searchParams.set('maxResults', '25');
        url.searchParams.set('key', apiKey);

        const response = await fetch(url.toString());
        const data = await response.json();

        if (!data.error && data.items && Array.isArray(data.items)) {
          const artistMap = new Map<string, ArtistSearchResult>();

          for (const item of data.items) {
            const rawChannel = decodeHtmlEntities(item.snippet?.channelTitle || '').trim();
            if (!rawChannel) continue;

            const isTopic = /-\s*topic$/i.test(rawChannel);
            const cleanName = cleanArtistName(rawChannel);
            const thumbnail =
              item.snippet?.thumbnails?.high?.url ||
              item.snippet?.thumbnails?.medium?.url ||
              item.snippet?.thumbnails?.default?.url ||
              '';

            if (!artistMap.has(cleanName)) {
              artistMap.set(cleanName, {
                id: item.snippet?.channelId || cleanName,
                name: cleanName,
                channelTitle: isTopic ? rawChannel : `${cleanName} - Topic`,
                thumbnail,
                description: 'Official Topic Channel',
              });
            }
          }

          if (artistMap.size > 0) {
            return Array.from(artistMap.values()).slice(0, maxResults);
          }
        }
      } catch (err: any) {
        this.logger.warn(`YouTube API artist search failed: ${err.message}`);
      }
    }

    // Fallback via yt-dlp
    try {
      const command = `yt-dlp --dump-single-json --flat-playlist --extractor-args "youtube:player_client=android" "ytsearch20:${searchQuery.replace(
        /"/g,
        '\\"',
      )}"`;
      const { stdout } = await execAsync(command, { maxBuffer: 10 * 1024 * 1024 });
      const data = JSON.parse(stdout);

      const artistMap = new Map<string, ArtistSearchResult>();
      for (const entry of data.entries || []) {
        const rawChannel = (entry.uploader || entry.channel || '').trim();
        if (!rawChannel) continue;

        const isTopic = /-\s*topic$/i.test(rawChannel);
        const cleanName = cleanArtistName(rawChannel);
        const thumbnail = entry.thumbnails?.[0]?.url || '';

        if (!artistMap.has(cleanName)) {
          artistMap.set(cleanName, {
            id: entry.channel_id || cleanName,
            name: cleanName,
            channelTitle: isTopic ? rawChannel : `${cleanName} - Topic`,
            thumbnail,
            description: 'Official Topic Channel',
          });
        }
      }

      return Array.from(artistMap.values()).slice(0, maxResults);
    } catch (error: any) {
      this.logger.error(`yt-dlp artist search error: ${error.message}`);
      return [];
    }
  }

  private async searchViaYoutubeApi(
    searchQuery: string,
    apiKey: string,
    maxResults: number,
  ): Promise<TrackSearchResult[]> {
    const fetchLimit = Math.max(maxResults * 2, 20);
    const url = new URL(`${this.baseUrl}/search`);
    url.searchParams.set('part', 'snippet');
    url.searchParams.set('type', 'video');
    url.searchParams.set('videoCategoryId', '10'); // 10 = Music category on YouTube
    url.searchParams.set('q', searchQuery);
    url.searchParams.set('maxResults', fetchLimit.toString());
    url.searchParams.set('key', apiKey);

    const response = await fetch(url.toString());
    const data = await response.json();

    if (data.error) {
      throw new Error(`YouTube API error: ${data.error.message}`);
    }

    if (!data.items || !Array.isArray(data.items)) {
      return [];
    }

    // Filter strictly for auto-generated YouTube topic tracks
    const filteredItems = data.items.filter((item: any) => {
      const channelTitle = item.snippet?.channelTitle || '';
      const description = item.snippet?.description || '';
      return isAutoGeneratedTrack(channelTitle, description);
    });

    return filteredItems.slice(0, maxResults).map((item: any) => {
      const videoId = item.id?.videoId;
      const snippet = item.snippet || {};
      const title = decodeHtmlEntities(snippet.title || '');
      const rawChannelTitle = decodeHtmlEntities(snippet.channelTitle || '');
      const artist = cleanArtistName(rawChannelTitle);
      const fallbackThumbnail = snippet.thumbnails?.high?.url || snippet.thumbnails?.medium?.url;
      const thumbnail = getHighResThumbnail(videoId, fallbackThumbnail);
      const description = formatDescription(snippet.description, artist);

      return {
        id: videoId,
        title,
        artist,
        thumbnail,
        url: `https://www.youtube.com/watch?v=${videoId}`,
        description,
      };
    });
  }

  private async searchViaYtDlp(
    searchQuery: string,
    maxResults: number,
  ): Promise<TrackSearchResult[]> {
    try {
      const fetchLimit = Math.max(maxResults * 2, 20);
      const command = `yt-dlp --dump-single-json --flat-playlist --extractor-args "youtube:player_client=android" "ytsearch${fetchLimit}:${searchQuery.replace(/"/g, '\\"')}"`;
      const { stdout } = await execAsync(command, { maxBuffer: 10 * 1024 * 1024 });
      const data = JSON.parse(stdout);

      const entries = data.entries || [];

      // Filter strictly for auto-generated YouTube topic tracks
      const filteredEntries = entries.filter((entry: any) => {
        const channelTitle = entry.uploader || entry.channel || '';
        const description = entry.description || '';
        return isAutoGeneratedTrack(channelTitle, description);
      });

      return filteredEntries.slice(0, maxResults).map((entry: any) => {
        const videoId = entry.id;
        const title = entry.title || 'Unknown Title';
        const rawChannelTitle = entry.uploader || entry.channel || '';
        const artist = cleanArtistName(rawChannelTitle);
        const fallbackThumbnail = entry.thumbnails?.[0]?.url;
        const thumbnail = getHighResThumbnail(videoId, fallbackThumbnail);
        const description = formatDescription(entry.description, artist);

        return {
          id: videoId,
          title,
          artist,
          thumbnail,
          url: `https://www.youtube.com/watch?v=${videoId}`,
          description,
        };
      });
    } catch (error: any) {
      this.logger.error(`yt-dlp search error: ${error.message}`);
      return [];
    }
  }
}
